jobs:
- job: linux
  pool: {vmImage: 'Ubuntu-16.04'}
  variables:
    CIBW_BUILD: 'cp35'
    #CIBW_PLATFORM: 'linux'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 3

  steps:
    - bash: |
        sudo apt-get update && sudo apt-get install -y libgsl-dev
        curl https://www.mpi-hd.mpg.de/personalhomes/globes/download/globes-3.2.17.tar.gz | tar xvz
        cd globes-3.2.17
        ./configure
        sudo make
        sudo make install
        sudo ldconfig
        cd ..
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
        addToPath: true
    - bash: |
        python -m pip install --upgrade pip setuptools wheel
        pip install six
        pip install cffi
        pip install cibuildwheel==0.11.1
        cibuildwheel --output-dir wheelhouse --platform linux .
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: 'wheelhouse'}
- job: macos
  pool: {vmImage: 'macOS-10.13'}
  steps:
    - bash: |
        curl https://www.mpi-hd.mpg.de/personalhomes/globes/download/globes-3.2.17.tar.gz | tar xvz
        cd globes-3.2.17
        ./configure
        make
        make install
        ldconfig
    - task: UsePythonVersion@0
    - bash: |
        python -m pip install --upgrade pip
        pip install cibuildwheel==0.11.1
        cibuildwheel --output-dir wheelhouse .
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: 'wheelhouse'}
