
pool:
  vmImage: 'ubuntu-16.04'

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'

- bash: sudo apt-get update && sudo apt-get install -y libgsl-dev
  workingDirectory: $(System.DefaultWorkingDirectory)
  displayName: download and update libgsl-dev
  failOnStderr: false

- bash: curl https://www.mpi-hd.mpg.de/personalhomes/globes/download/globes-3.2.17.tar.gz | tar xvz
  workingDirectory: $(System.DefaultWorkingDirectory)
  displayName: dowload and extract globes library
  failOnStderr: false

- bash: ./configure --prefix=$(GLB_DIR)
  workingDirectory: $(System.DefaultWorkingDirectory)/globes-3.2.17
  displayName: configure globes library
  failOnStderr: false

- bash: sudo make
  workingDirectory: $(System.DefaultWorkingDirectory)/globes-3.2.17
  displayName: make globes library
  failOnStderr: false

- bash: sudo make install
  workingDirectory: $(System.DefaultWorkingDirectory)/globes-3.2.17
  displayName: install globes library
  failOnStderr: false

- bash: sudo ldconfig
  workingDirectory: $(System.DefaultWorkingDirectory)/globes-3.2.17
  displayName: run ldconfig
  failOnStderr: false

- bash: globes-config --include
  workingDirectory: $(System.DefaultWorkingDirectory)
  displayName: includes
  failOnStderr: false
